:sectnums:

= Sampler

The purpose of the project is to provide a working sample for the general structure of a project.

include::docs/requirements.adoc[leveloffset=+1]

== Sample services
All services use the same API, run on the same port, and in the same environment.

=== REST service
sample/sample-rest-service

This is a simple basic REST implementation. It only uses essential technologies. Every other sample service is essentially an extension of this.

=== JPA service
sample/sample-jpa-service

The purpose of this service is to demonstrate the use of JPA. Since it is designed to be universal, it uses an H2 database, but entity management is similar to a regular DB.

=== Mongo service
sample/sample-mongo-service

The purpose of this service is to showcase the usage of MongoDB for simple read/write operations. The service is built on the coff:ee mongo module, and more information about it can be found here: https://i-cell-mobilsoft-open-source.github.io/coffee/#common_module_coffee-module-mongodb

To use the service, you first need to run the Dockerized MongoDB database.

== Execution
Execution is done using Docker Compose because it allows for more advanced configurations than using Docker alone.

.Service server - starting the environment
[source,bash]
----
docker-compose -f local_path/sampler/etc/docker-compose/docker-compose.local.wildfly.yml up --force-recreate
----
The --force-recreate option is used to delete the previous Docker container during startup, ensuring a clean environment for each launch.

.War deploy - Installation
This utilizes Wildfly's deploy autoscan feature, which means we copy the WAR file into the scanned directory. This can be done through the console (not convenient) or using an ANT file (sample/sample-*-service/build.xml). The Wildfly server and its configuration are set to run only one service at a time. So you can use the following "copy" script for installation, where you need to set the <PROJECT_VERSION> to the current version number:

.war file installation
[source,bash]
----
# For sample-rest-service
docker cp local_path/sample/sample-rest-service/target/sample-rest-service-<PROJECT_VERSION>.war bs-sample-service:/opt/jboss/wildfly/standalone/deployments/ROOT.war

# For sample-jpa-service
docker cp local_path/sample/sample-jpa-service/target/sample-jpa-service-<PROJECT_VERSION>.war bs-sample-service:/opt/jboss/wildfly/standalone/deployments/ROOT.war

# For sample-mongo-service
docker cp local_path/sample/sample-mongo-service/target/sample-mongo-service-<PROJECT_VERSION>.war bs-sample-service:/opt/jboss/wildfly/standalone/deployments/ROOT.war
----

Alternatively, using Ant from your IDE with just one click is more convenient. For example, in the sample/sample-rest-service/build.xml ANT file, you can use the - "deploy-war-docker" target (default). It handles the paths, version numbers, and you don't need to remember anything, open a console, etc.

Some services, like sample-mongo-service, require the MongoDB service. For this, the etc/docker-compose/docker-compose.local.mongodb.yml Docker Compose file is prepared. To start it, you simply need to execute the following command:

.MongoDB
[source,bash]
----
docker-compose -f local_path/sampler/etc/docker-compose/docker-compose.local.mongodb.yml up --force-recreate
----
Everything else is already set up.

== Testing
The endpoints are not authenticated, you can use the SwaggerUI page. Unfortunately, due to the complexity of the API, the XML format will not work well due to XML namespace issues. Therefore, it is recommended to use the JSON format.

.Developer tests - sr-testsuite
`sampler/sr-testsuite`

Development tests use the https://github.com/i-Cell-Mobilsoft-Open-Source/roaster[Roaster] project.
It is a fully self-contained REST that makes external calls to the deployed application.
It can be run immediately using the developer UI (junit pligun) or maven (the "profile" switch must be activated),
for example:

[source,bash]
----
mvn verify -Dprofile <1>
mvn verify -Dprofile=sandbox,local <2>
----
<1> default parameters
<2> selected profiles from configuration files