mp:
  messaging:
    connector:
      smallrye-kafka:
        bootstrap:
          servers: bs-kafka:9092
    outgoing:
      to-kafka-avro:
        connector: smallrye-kafka
        topic: testing-avro
        key:
          serializer: org.apache.kafka.common.serialization.IntegerSerializer
        value:
          serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
        schema:
          registry:
            url: http://bs-schema-registry:8085
      to-kafka-string:
        connector: smallrye-kafka
        # The following parameters have effect for each other so we need to take into consideration of theirs settings to avoid the next error message:
        # delivery.timeout.ms should be equal to or larger than linger.ms + request.timeout.ms
        # the connector will try to resend those records that was not delivered successfully
        retries: 0
        # https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/producer/ProducerConfig.java#L158
        # this should be correlated with the REST timeout (e.g. 1 min)
        delivery:
          timeout:
            ms: 5000
        # https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/producer/ProducerConfig.java#L139
        linger:
          ms: 1000
        # https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/producer/ProducerConfig.java#L152
        request:
          timeout:
            ms: 500
        topic: testing-string
        key:
          serializer: org.apache.kafka.common.serialization.IntegerSerializer
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer
        interceptor:
          classes:
            - hu.icellmobilsoft.sampler.sample.kafka.service.kafka.interceptor.OutgoingHeaderInterceptor
            - hu.icellmobilsoft.sampler.sample.kafka.service.kafka.interceptor.OutgoingLoggingInterceptor
    incoming:
      from-kafka-avro:
        connector: smallrye-kafka
        topic: testing-avro
        value:
          deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        key:
          deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
        schema:
          registry:
            url: http://bs-schema-registry:8085
        specific:
          avro:
            reader: true
      from-kafka-string:
        connector: smallrye-kafka
        topic: testing-string
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        key:
          deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
        interceptor:
          classes:
            - hu.icellmobilsoft.sampler.sample.kafka.service.kafka.interceptor.IncomingHeaderInterceptor
            - hu.icellmobilsoft.sampler.sample.kafka.service.kafka.interceptor.IncomingLoggingInterceptor
