{
 "title": "gRPC mp metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "gRPC server metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "gRPC request message received",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "application_coffee_grpc_server_requests_received_messages_total{job=\"bs-sample-service-job\"}",
     "legendFormat": "{{method}}-{{methodType}}-{{service}}"
    }
   ]
  },
  {
   "title": "gRPC response message sent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "application_coffee_grpc_server_responses_sent_messages_total{job=\"bs-sample-service-job\"}",
     "legendFormat": "{{method}}-{{methodType}}-{{service}}"
    }
   ]
  },
  {
   "title": "gRPC server processing duration via status mean seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "application_coffee_grpc_server_processing_duration_seconds_mean_seconds{job=\"bs-sample-service-job\"}",
     "legendFormat": "{{method}}-{{methodType}}-{{service}}-{{status}}"
    }
   ]
  },
  { "title": "gRPC client metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "gRPC client request message sent",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "application_coffee_grpc_client_requests_sent_messages_total{job=\"bs-sample-service-job\"}",
     "legendFormat": "{{method}}-{{methodType}}-{{service}}"
    }
   ]
  },
  {
   "title": "gRPC client response message received",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "application_coffee_grpc_client_responses_received_messages_total{job=\"bs-sample-service-job\"}",
     "legendFormat": "{{method}}-{{methodType}}-{{service}}"
    }
   ]
  },
  {
   "title": "gRPC client processing duration via status mean seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "application_coffee_grpc_client_processing_duration_seconds_mean_seconds{job=\"bs-sample-service-job\"}",
     "legendFormat": "{{method}}-{{methodType}}-{{service}}-{{status}}"
    }
   ]
  }
 ]
}