{
 "title": "redis stream metrics",
 "tags": [ "provisioned" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_network_receive_packets_total{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{namespace=~\"$namespace\"},app_kubernetes_io_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Consumer count",
   "type": "timeseries",
   "description": "The number of consumers in the redis stream",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_stream_group_consumers{namespace=\"$namespace\"}",
     "legendFormat": "{{stream}} ({{configKey}})"
    }
   ]
  },
  {
   "title": "Stream size",
   "type": "timeseries",
   "description": "The number of entries in the redis stream (see XLEN)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "redis_stream_length{namespace=\"$namespace\"}",
     "legendFormat": "{{stream}} ({{configKey}})"
    }
   ]
  },
  {
   "title": "Added message count",
   "type": "timeseries",
   "description": "The cardinality of messages added to stream, since running",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "application_stream_added_message_count{namespace=\"$namespace\"}",
     "legendFormat": "{{stream}} ({{configKey}})"
    }
   ]
  },
  {
   "title": "Read message count",
   "type": "timeseries",
   "description": "The cardinality of messages read by consumers connected to stream, since running",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "redis_stream_group_entries_read{namespace=\"$namespace\"}",
     "legendFormat": "{{stream}} ({{configKey}})"
    }
   ]
  },
  {
   "title": "Lagging message count",
   "type": "timeseries",
   "description": "The cardinality of messages not yet red by consumers connected to stream",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "redis_stream_group_lag{namespace=\"$namespace\"}",
     "legendFormat": "{{stream}} ({{configKey}})"
    }
   ]
  },
  {
   "title": "Pending message count",
   "type": "timeseries",
   "description": "The length of the redis stream's pending entries list (PEL), which are messages that were delivered but are yet to be acknowledged",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "redis_stream_group_messages_pending{namespace=\"$namespace\"}",
     "legendFormat": "{{stream}} ({{configKey}})"
    }
   ]
  }
 ]
}