name: backend-sampler

# futtatas
# docker-compose -f <PROJECT_PATH>/backend-sampler/etc/docker-compose/docker-compose.local.wildfly-postgresql.yml up --build --force-recreate
#
# belemaszas
# docker exec -it bs-sample-service /bin/bash
#
# uresbe inditas
# docker run --rm -it docker-compose_sample-service /bin/bash
services:
  sample-service:
    container_name: bs-sample-service
    # jboss-deployment-structure.xml + beanutils dep needed
    # image: icellmobilsoft/wildfly-mp-jpa-postgresql-jdbc:4.0.0-SNAPSHOT
    # full image, the server contains beanutils, collections libraries, and the netty extension bug is not appearing due to some transitive dep...
    image: icellmobilsoft/wildfly-mp-full-postgresql-jdbc:4.0.0-SNAPSHOT
    ports:
      - '8081:8080'
      - '9991:9990'
      - '8788:8787'
    environment:
      # POSTGRESQL
      POSTGRESQL_DS_CONNECTION_URL: jdbc:postgresql://bs-postgres:5432/bs_sample_service
      POSTGRESQL_DS_USERNAME: bs_sample_service
      POSTGRESQL_DS_PASSWORD: bs_sample_service
      HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      # OPEN TELEMETRY
      OTEL_SERVICE_NAME: bs-sample-service
      OPENTELEMETRY_SERVICE_NAME: bs-sample-service
      OPENTELEMETRY_SAMPLER_TYPE: on
      OPENTELEMETRY_EXPORTER_TYPE: otlp
      OPENTELEMETRY_EXPORTER_ENDPOINT: http://opentelemetry-collector:4317
      MICROMETER_ENDPOINT: http://opentelemetry-collector:4318/v1/metrics
      # OTHER
      MP_CONFIG_PROFILE: jdbc
      DEBUG: true
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
networks:
  default:
    name: bs-local-network
