version: "3"

# run from project directory
# docker-compose -f ./etc/docker-compose/docker-compose.local.kafka.yml up --build --force-recreate
services:
  kafka:
    container_name: bs-kafka
    # https://hub.docker.com/r/bitnami/kafka
    # based on debian
    image: bitnami/kafka:3.5.1
    ports:
      - 9092:9092
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@bs-kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_CLIENT_USERS: user #Default: user
#      KAFKA_CLIENT_PASSWORDS: password #Default: bitnami
#      KAFKA_CONTROLLER_USER: controller_user #Default: controller_user
#      KAFKA_CONTROLLER_PASSWORD: controller_password #Default: bitnami
    volumes:
      - bs-kafka-persistence:/bitnami/kafka
  kafka-ui:
    container_name: bs-kafka-ui
    image: provectuslabs/kafka-ui:v0.7.1
    ports:
      - 9080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      # https://docs.kafka-ui.provectus.io/configuration/configuration-file
      KAFKA_CLUSTERS_0_NAME: bs-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: bs-kafka:9092
volumes:
  bs-kafka-persistence:
    name: bs-kafka-persistence
networks:
  default:
    external:
      # if it could not be found on compose up, then execute: docker network create bs-local-network
      name: bs-local-network
