sampler:
    service:
        sample:
            base:
                uri: http://localhost:8081
            management:
                uri: http://localhost:9991
testsuite:
    rest:
        sampleService:
            sample:
                baseUriKey: sampler.service.sample.base.uri
                path: /rest/sample
            management:
                health:
                    baseUriKey: sampler.service.sample.management.uri
                    path: /health

coffee:
  redis:
    sample:
      host: localhost
      port: 6379
      database: 0
      pool:
        default:
          maxidle: 32
          maxtotal: 128

roaster:
    hibernate:
        defaultPU:
            jdbc:
                driver: org.postgresql.Driver
                url: jdbc:postgresql://localhost:5432/bs_sample_service
                user: bs_sample_service
                password: bs_sample_service
            hibernate:
                default_schema: public
                dialect: org.hibernate.dialect.PostgreSQLDialect
                show_sql: true
                format_sql: true
