= Kafka service
`sample/sample-kafka-service`

The purpose of the service is to demonstrate the usage of Kafka handling with simple usage examples.

How to use the service

. You need to run Dockerized Kafka.
+
For example.: `docker compose up -f etc/docker-compose/docker-compose.local.kafka.yml up -d`
. Start the docker-compose.local.wildfly.yml with MicroProfile Reactive WildFly modules.
* You can achieve this by setting the SERVICE_CLI_DIR build argument to wildfly/cli/mp-reactive in the compose file.
+
[source,yaml]
----
services:
  sample-service:
    container_name: bs-sample-service
    build:
      context: .
      dockerfile: develop.dockerfile
      args:
        WILDFLY_BASE_IMAGE: 'quay.io/wildfly/wildfly:27.0.0.Final-jdk17'
#        Run custom CLI scripts if required for deployment.
        SERVICE_CLI_DIR: 'wildfly/cli/mp-reactive'
    environment:
      MP_CONFIG_PROFILE: kafka
----
It is necessary to use the "kafka" MicroProfile Config profile switch 
because the configuration might clash with other examples.

== Endpoints

=== GET `/rest/sample`

Currently not bound to Kafka functionality.

=== POST `/rest/sample`

. Sends and reads messages to/from the testing Kafka topic.
