= Redis pub-sub service
`sample/sample-redispubsub-service`

The purpose of the service is to demonstrate the usage of Redis Pub/Sub handling with a simple publish/subscribe pattern.
The service is built on the coff:ee Redis Pub/Sub module. For more information, you can find details here: https://i-cell-mobilsoft-open-source.github.io/coffee/#common_module_coffee-module-redispubsub

How to use the service

. You need to run Dockerized Redis.
+
For example.: `docker-compose up -f etcd/docker-compose/docker-compose.local.redis.yml up -d`
. Start the docker-compose.local.wildfly.yml with Pub-Sub ready WildFly modules.
* You can achieve this by setting the SERVICE_CLI_DIR build argument to `wildfly/cli/mp-reactive` in the compose file.
+
[source,yaml]
----
services:
  sample-service:
    container_name: bs-sample-service
    build:
      context: .
      dockerfile: develop.dockerfile
      args:
        WILDFLY_BASE_IMAGE: 'quay.io/wildfly/wildfly:27.0.0.Final-jdk17'
#        Custom CLI scripts can be executed if needed for deployment.
        SERVICE_CLI_DIR: 'wildfly/cli/mp-reactive'
    environment:
      MP_CONFIG_PROFILE: redispubsub
----
The "redispubsub" MicroProfile Config profile switch is necessary 
because the configuration might conflict with other examples.

== Endpoints

=== GET `/rest/sample`

The response returns the last read value from the `sample-get` Redis channel in the `columnA` field.
(`GetListener` reads and stores in `ApplicationContainer`, from where REST retrieves the value).

To publish a message to the channel using redis-cli:

[source, shell]
----
docker exec -it bs-sample-redis redis-cli
127.0.0.1:6379> PUBLISH sample-get test-dummy
----


=== POST `/rest/sample`

. Üzenetet küld a `sample-post` és `no-sub` redis channelekre.
Sends a message to the `sample-post` and `no-sub` Redis channels.
. `PostInListener` reads from the `sample-post` channel, caches the received message in 
`ApplicationContainer`, and forwards it (again) to the `no-sub` Redis channel.
. REST waits for 1 second during processing, then retrieves the message from `ApplicationContainer`. If not found, it throws a BONotFound error.

To subscribe to the no-sub channel using redis-cli:
[source, shell]
----
docker exec -it bs-sample-redis redis-cli
127.0.0.1:6379> SUBSCRIBE no-sub
----




