= Redis pub-sub service
`sample/sample-redispubsub-service`

A service célja a redis Pub/Sub kezelés használatának bemutatása egyszerű publish/subscribe mintával.
A service a coff:ee redispubsub moduljára épül, erről bővebb információ itt található: https://i-cell-mobilsoft-open-source.github.io/coffee/#common_module_coffee-module-redispubsub

A service használata

. futtatni kell a dockeres redist.
+
pl.: `docker-compose up -f etcd/docker-compose/docker-compose.local.redis.yml up -d`
. docker-compose.local.wildfly.yml-t pub-sub ready widlfly modulokkal kell elindítani
* ezt a compose fájlban a SERVICE_CLI_DIR build arg `wildfly/cli/mp-reactive`-ra állításával tehetjük meg
+
[source,yaml]
----
services:
  sample-service:
    container_name: bs-sample-service
    build:
      context: .
      dockerfile: develop.dockerfile
      args:
        WILDFLY_BASE_IMAGE: 'quay.io/wildfly/wildfly:26.1.1.Final'
#        custom cli script futtatása, ha a deploymenthez kell
        SERVICE_CLI_DIR: 'wildfly/cli/mp-reactive'
----

== Végpontok

=== GET `/rest/sample`

A válasz `columnA` mezőjében visszaadja `sample-get` redis channelről utoljára olvasott értéket
(`GetListener` olvas és `ApplicationContainer`-be ment, innen veszi a REST az értéket).

A channelre beküldeni redis-cli-vel tudunk pl.:

[source, shell]
----
docker exec -it bs-sample-redis redis-cli
127.0.0.1:6379> PUBLISH sample-get test-dummy
----


=== POST `/rest/sample`

. Üzenetet küld a `sample-post` és `no-sub` redis channelekre.
. a `PostInListener` olvas a `sample-post` channelről, a kapott üzenetet cacheli `ApplicationContainer`-be
és tovább küldi (mégegyszer) a `no-sub` redis channelre.
. a REST közben vár 1 sec-et, majd kiolvassa az `ApplicationContainer`-ből az üzenetet - vagy BONotFound-ot dob, ha nem találja

Ha szeretnénk a `no-sub` channelre redis-cli-vel fel tudunk iratkozni.
[source, shell]
----
docker exec -it bs-sample-redis redis-cli
127.0.0.1:6379> SUBSCRIBE no-sub
----




